NicePictureStudio/NicePictureStudioWeb/Controllers/LocationSchedulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NicePictureStudio.App_Data;
using Kendo.Mvc.UI;
using NicePictureStudio.Models;
using Kendo.Mvc.Extensions;
using NicePictureStudio.Utils;
using System.Text.RegularExpressions;

namespace NicePictureStudio
{
    public class LocationSchedulesController : Controller
    {
        private NicePictureStudioDBEntities db = new NicePictureStudioDBEntities();

        // GET: LocationSchedules
        public async Task<ActionResult> Index()
        {
            //Employee Management
            var _empList = db.Employees.Where(e => e.EmployeePositions.Any(em => em.Id == Constant.EMPLOYEE_POSITION_PHOTOGRAPH
                || em.Id == Constant.EMPLOYEE_POSITION_CAMERAMAN)).ToList();
            Employee defaultEmp = new Employee
            {
                Id = "",
                Name = "เลือกทั้งหมด"
            };
            _empList.Insert(0, defaultEmp);

            //Service Management
            var _serviceTypeList = db.ServiceTypes.ToList();
            ServiceType defaultServiceType = new ServiceType { Id = Constant.DEFAULT, ServiceTypeName = "เลือกทั้งหมด" };
            _serviceTypeList.Insert(0, defaultServiceType);

            //Status Management
            var _statusList = db.ServiceStatus.ToList();
            ServiceStatu defaultStatus = new ServiceStatu { Id = Constant.DEFAULT, StatusName = "เลือกทั้งหมด" };
            _statusList.Insert(0, defaultStatus);

            ViewBag.EmployeeList = new SelectList(_empList, "Id", "Name");
            ViewBag.ServiceTypeList = new SelectList(_serviceTypeList, "Id", "ServiceTypeName");
            ViewBag.StatusList = new SelectList(_statusList, "Id", "StatusName");
            return View(await db.LocationSchedules.ToListAsync());
        }

        // GET: LocationSchedules/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LocationSchedule locationSchedule = await db.LocationSchedules.FindAsync(id);
            if (locationSchedule == null)
            {
                return HttpNotFound();
            }
            return View(locationSchedule);
        }

        // GET: LocationSchedules/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LocationSchedules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,StartTime,EndTime,LocationId,LocationServiceId,Status")] LocationSchedule locationSchedule)
        {
            if (ModelState.IsValid)
            {
                db.LocationSchedules.Add(locationSchedule);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(locationSchedule);
        }

        // GET: LocationSchedules/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LocationSchedule locationSchedule = await db.LocationSchedules.FindAsync(id);
            if (locationSchedule == null)
            {
                return HttpNotFound();
            }
            return View(locationSchedule);
        }

        // POST: LocationSchedules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,StartTime,EndTime,LocationId,LocationServiceId,Status")] LocationSchedule locationSchedule)
        {
            if (ModelState.IsValid)
            {
                db.Entry(locationSchedule).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(locationSchedule);
        }

        // GET: LocationSchedules/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LocationSchedule locationSchedule = await db.LocationSchedules.FindAsync(id);
            if (locationSchedule == null)
            {
                return HttpNotFound();
            }
            return View(locationSchedule);
        }

        // POST: LocationSchedules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            LocationSchedule locationSchedule = await db.LocationSchedules.FindAsync(id);
            db.LocationSchedules.Remove(locationSchedule);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public PartialViewResult LocationScheduler(string photographId, int? serviceTypeId, int? statusId, bool? isConfirm, bool? isNotFinish)
        {
            ViewBag.PhotographerId = photographId == string.Empty ? Constant.UNDEFINED : photographId;
            ViewBag.ServiceTypeId = serviceTypeId == null ? Constant.DEFAULT : serviceTypeId;
            ViewBag.Status = statusId == null ? Constant.DEFAULT : statusId;
            ViewBag.IsConfirm = isConfirm == null ? false : isConfirm;
            ViewBag.IsNotFinish = isNotFinish == null ? false : isNotFinish;
            return PartialView();
        }

        public virtual JsonResult Locations_Read([DataSourceRequest] DataSourceRequest request, string phothgraphId, int serviceTypeId, int? statusId, bool? isConfirm, bool? isNotFinish)
        {
            IQueryable<SchedulerViewModels> tasks = CreateLocationSchedules(phothgraphId, serviceTypeId, statusId, isConfirm, isNotFinish).Select(task => new SchedulerViewModels()
            {
                Id = task.Id,
                Title = task.Title,
                Description = task.Description,
                Start = task.Start,
                End = task.End,
                StartTimezone = task.StartTimezone,
                EndTimezone = task.EndTimezone,
                IsAllDay = task.IsAllDay,
                Recurrence = task.Recurrence,
                RecurrenceException = task.RecurrenceException,
                selectedStatus = task.selectedStatus
            }
            ).AsQueryable();
            return Json(tasks.ToDataSourceResult(request));
        }

        private List<SchedulerViewModels> CreateLocationSchedules(string photographId, int? serviceTypeId, int? statusId, bool? isConfirm, bool? isNotFinish)
        {
            int statuLocationInvalid = Constant.LOCATION_STATUS_CLOSED;
            List<SchedulerViewModels> _listSchecule = new List<SchedulerViewModels>();
            var allLocation = (from locatonSchedule in db.LocationSchedules
                               join loc in db.Locations on locatonSchedule.LocationId equals loc.LocationId
                               where (loc.LocationStatu.Id != statuLocationInvalid)
                               select new { locSchedule = locatonSchedule, location = loc }).ToList();

            //Add condition for filtering
            var filterServiceForms = allLocation;
            if (photographId != Constant.UNDEFINED && photographId != null)
            {
                filterServiceForms = filterServiceForms.Where(s => s.locSchedule.ServiceForm.EmployeeSchedules.Any(ems=>ems.Employee.Id == photographId)).Select(s => s).ToList();
            }

            if (serviceTypeId > 0 && statusId != null)
            {
                filterServiceForms = filterServiceForms.Where(s => s.locSchedule.ServiceForm.ServiceType.Id == serviceTypeId).ToList();
            }

            if (statusId > 0 && statusId != null)
            {
                filterServiceForms = filterServiceForms.Where(s => s.locSchedule.Status == statusId).ToList();
            }

            if (isConfirm != null)
            {
                if (isConfirm == true && statusId < Constant.SERVICE_STATUS_NEW)
                { filterServiceForms = filterServiceForms.Where(s => s.locSchedule.Status <= Constant.SERVICE_STATUS_CONFIRM).ToList(); }
            }

            if (isNotFinish != null)
            {
                if (isNotFinish == true && statusId < Constant.SERVICE_STATUS_NEW)
                {
                    var currentDate = DateTime.Now;
                    filterServiceForms = filterServiceForms.Where(s => (s.locSchedule.StartTime - currentDate).TotalDays > 3 && s.locSchedule.Status <= Constant.SERVICE_STATUS_CONFIRM).ToList();
                }
            }
            //Add condition for filtering

            foreach (var item in filterServiceForms)
            {
                if (item.locSchedule.ServiceForm != null)
                {
                    SchedulerViewModels _scheduler = new SchedulerViewModels
                    {
                        Id = item.locSchedule.Id,
                        Title = item.location.LocationName,
                        Description = item.location.Detail,
                        Start = item.locSchedule.StartTime,

NicePictureStudio/NicePictureStudioWeb/Views/LocationSchedules/Create.cshtml
@model NicePictureStudio.App_Data.LocationSchedule

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>LocationSchedule</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LocationId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LocationId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LocationServiceId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LocationServiceId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LocationServiceId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

NicePictureStudio/NicePictureStudioWeb/Views/LocationSchedules/Delete.cshtml
@model NicePictureStudio.App_Data.LocationSchedule

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>LocationSchedule</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.StartTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.StartTime)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EndTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EndTime)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LocationId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LocationId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LocationServiceId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LocationServiceId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

NicePictureStudio/NicePictureStudioWeb/Views/LocationSchedules/Details.cshtml
@model NicePictureStudio.App_Data.LocationSchedule

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>LocationSchedule</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.StartTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.StartTime)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EndTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EndTime)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LocationId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LocationId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LocationServiceId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LocationServiceId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

NicePictureStudio/NicePictureStudioWeb/Views/LocationSchedules/Edit.cshtml
@model NicePictureStudio.App_Data.LocationSchedule

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>LocationSchedule</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LocationId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LocationId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LocationServiceId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LocationServiceId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LocationServiceId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

NicePictureStudio/NicePictureStudioWeb/Views/LocationSchedules/Index.cshtml
@model IEnumerable<NicePictureStudio.App_Data.LocationSchedule>

<script type="text/javascript">
    kendo.culture("th-TH");
    $(document).ready(function () {
        $("#statusId").on("change", function () {
            if ($("#statusId").val() >1)
            {
                $("#isConfirm").attr("disabled", "disabled");
                $("#isNotFinish").attr("disabled", "disabled");
                $("#lblIsConfirm").css("color", "#d2cdcd");
                $("#lblIsNotFinish").css("color", "#d2cdcd");
                $("#isNotFinish").attr("checked", false);
            }
            else if ($("#statusId").val() <= 1)
            {
                $("#isConfirm").attr("disabled", null);
                $("#isNotFinish").attr("disabled", null);
                $("#lblIsConfirm").css("color", "");
                $("#lblIsNotFinish").css("color", "");
            }
        });

        $("#ClearResult").on("click", function () {
            $("#isConfirm").attr("disabled", null);
            $("#isNotFinish").attr("disabled", null);
            $("#lblIsConfirm").css("color", "");
            $("#lblIsNotFinish").css("color", "");
        });
    });

    function modelOpen() {
        var serviceIndex = $(".IdLocSchedule").val();
        $.ajax({
            url: '@Url.Action("DetailsLocation", "LocationSchedules")',
            data: { locScheduleId: serviceIndex },
            type: "POST",
            success: function (data) {
                $(".nccontainer").html(data);
                $(".ncmodal").modal('toggle');

            }
        });
    }
</script>

<h2>ตารางงานสถานที่ถ่ายภาพ บริษัท รูปสวยโฟโต้จำกัด</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<div class="panel-default table-bordered">
    <div class="panel-title"></div>
    <div class="panel-heading">ตัวเลือกในการค้นหาข้อมูล</div>
    <div class="panel-body">
        @using (Ajax.BeginForm("LocationScheduler", "LocationSchedules", new AjaxOptions
                        {
                            HttpMethod = "GET",
                            InsertionMode = InsertionMode.Replace,
                            UpdateTargetId = "ServiceFormsScheduler"
                        }))
        {
            <table class="table-responsive table">
                <tr>
                    <td>
                        <div class="form-horizontal">
                            <div class="form-group-sm">
                                <div class="col-sm-12 col-xs-3">@Html.Label("รายชื่อพนักงาน")</div>

                                <div class="col-sm-12 col-xs-3">@(Html.Kendo().DropDownList().Name("photographId").BindTo(@ViewBag.EmployeeList as SelectList).HtmlAttributes(new { @style = "width:180px" }))</div>                                
                            </div>

                        </div>
                    </td>
                    <td>
                        <div class="col-sm-12 col-xs-3">@Html.Label("ประเภทของบริการ") </div>

                        <div class="col-sm-12 col-xs-3">@(Html.Kendo().DropDownList().Name("serviceTypeId").BindTo(@ViewBag.ServiceTypeList as SelectList).HtmlAttributes(new { @style = "width:160px" }))</div>
                    </td>
                    <td>
                        <div class="col-sm-12 col-xs-3">@Html.Label("สถานะ")</div>

                        <div class="col-sm-12 col-xs-3">@(Html.Kendo().DropDownList().Name("statusId").BindTo(@ViewBag.StatusList as SelectList).HtmlAttributes(new { @class = "statusId", @style = "width:150px" }))</div>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <hr />
                        <div class="form-horizontal">
                            <div class="panel-default table-bordered">
                                <div class="panel-heading">ตัวเลือกสำหรับรายการที่ยังไม่เสร็จสิ้นการให้บริการ</div>
                                <div class="panel-body">
                                    <div class="form-group-sm hidden">
                                        <div class="col-sm-1 col-xs-1 text-right"> @Html.CheckBox("isConfirm", false, new { @class = "form-contorl", @id = "isConfirm" })</div>
                                        <div class="col-sm-11 col-xs-5 text-left">@Html.Label("เลือกรายการที่ยังไม่ได้รับการยืนยันจากพนักงาน", new { @id = "lblIsConfirm" })</div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-1 col-xs-1 text-right"> @Html.CheckBox("isNotFinish", false, new { @class = "form-contorl", @id = "isNotFinish" })</div>
                                        <div class="col-sm-7 col-xs-11 text-left">@Html.Label("เลือกรายการที่ยังไม่เสร็จสิ้นและใกล้ถึงเวลาที่กำหนด", new { @id = "lblIsNotFinish" })</div>
                                    </div>
                                </div>
                            </div>

                        </div>

                    </td>
                </tr>
                <tr>
                    <td>
                        <button type="submit" value="GenerateFileter" class="btn-primary btn-md">เริ่มต้นค้นหา</button>
                        <button type="reset" id="ClearResult" value="GenerateFileter" class="btn-default btn-md">ล้างข้อมูลการค้นหา</button>
                    </td>
                </tr>
            </table>
        }
    </div>
</div>
<hr />
<div id="ServiceFormsScheduler">
    @{Html.RenderAction("LocationScheduler", "LocationSchedules");}
</div>


<div class="modal fade ncmodal" id="NavPattern" tabindex="-10" role="dialog"
     aria-labelledby="NavService" aria-hidden="true" data-url='' data-servicetype="" style="position:fixed;z-index:10004">
    <div class="modal-dialog modal-lg" style="width:90%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">
                    ×
                </button>
                <h4 class="modal-title" id="NavModelPattern">
                    รายงานสถานที่ในการถ่ายภาพ บริษัทรูปสวยโฟโต้ จำกัด
                </h4>
            </div>
            <div class="modal-body">
                <div id="NavPatternBody" class="nccontainer"></div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnPrint" class="btn btn-default" onclick="PrintX()">พิมพ์</button>
                <button id="btnCancelPattern" type="button" class="btn btn-default"
                        data-dismiss="modal">
                    ปิดรายการ
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



    @*<p>
        @Html.ActionLink("Create New", "Create")
    </p>
    @{Html.RenderAction("LocationScheduler", "LocationSchedules");}
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StartTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LocationId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LocationServiceId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocationId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocationServiceId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>*@