NicePictureStudio/NicePictureStudioWeb/Controllers/EmployeeSchedulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NicePictureStudio.App_Data;
using Kendo.Mvc.UI;
using NicePictureStudio.Models;
using Kendo.Mvc.Extensions;
using NicePictureStudio.Utils;
using System.Text.RegularExpressions;

namespace NicePictureStudio
{
    public class EmployeeSchedulesController : Controller
    {
        private NicePictureStudioDBEntities db = new NicePictureStudioDBEntities();

        // GET: EmployeeSchedules
        public async Task<ActionResult> Index()
        {
            //Employee Management
            var _empList = db.Employees.Where(e => e.EmployeePositions.Any(em => em.Id == Constant.EMPLOYEE_POSITION_PHOTOGRAPH
                || em.Id == Constant.EMPLOYEE_POSITION_CAMERAMAN)).ToList();
            Employee defaultEmp = new Employee
            {
                Id = "",
                Name = "เลือกทั้งหมด"
            };
            _empList.Insert(0, defaultEmp);

            //Service Management
            var _serviceTypeList = db.ServiceTypes.ToList();
            ServiceType defaultServiceType = new ServiceType { Id = Constant.DEFAULT, ServiceTypeName = "เลือกทั้งหมด" };
            _serviceTypeList.Insert(0, defaultServiceType);

            //Status Management
            var _statusList = db.ServiceStatus.ToList();
            ServiceStatu defaultStatus = new ServiceStatu { Id = Constant.DEFAULT, StatusName = "เลือกทั้งหมด" };
            _statusList.Insert(0, defaultStatus);

            ViewBag.EmployeeList = new SelectList(_empList, "Id", "Name");
            ViewBag.ServiceTypeList = new SelectList(_serviceTypeList, "Id", "ServiceTypeName");
            ViewBag.StatusList = new SelectList(_statusList, "Id", "StatusName");
            return View(await db.EmployeeSchedules.ToListAsync());
        }

        // GET: EmployeeSchedules/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeSchedule employeeSchedule = await db.EmployeeSchedules.FindAsync(id);
            if (employeeSchedule == null)
            {
                return HttpNotFound();
            }
            return View(employeeSchedule);
        }

        // GET: EmployeeSchedules/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EmployeeSchedules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,StartTime,EndTime,EmployeeServiceId")] EmployeeSchedule employeeSchedule)
        {
            if (ModelState.IsValid)
            {
                db.EmployeeSchedules.Add(employeeSchedule);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(employeeSchedule);
        }

        // GET: EmployeeSchedules/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeSchedule employeeSchedule = await db.EmployeeSchedules.FindAsync(id);
            if (employeeSchedule == null)
            {
                return HttpNotFound();
            }
            return View(employeeSchedule);
        }

        // POST: EmployeeSchedules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,StartTime,EndTime,EmployeeServiceId")] EmployeeSchedule employeeSchedule)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employeeSchedule).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(employeeSchedule);
        }

        // GET: EmployeeSchedules/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeSchedule employeeSchedule = await db.EmployeeSchedules.FindAsync(id);
            if (employeeSchedule == null)
            {
                return HttpNotFound();
            }
            return View(employeeSchedule);
        }

        // POST: EmployeeSchedules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            EmployeeSchedule employeeSchedule = await db.EmployeeSchedules.FindAsync(id);
            db.EmployeeSchedules.Remove(employeeSchedule);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public PartialViewResult EmployeesScheduler(string photographId, int? serviceTypeId, int? statusId, bool? isConfirm, bool? isNotFinish)
        {
            ViewBag.PhotographerId = photographId == string.Empty ? Constant.UNDEFINED : photographId;
            ViewBag.ServiceTypeId = serviceTypeId == null ? Constant.DEFAULT : serviceTypeId;
            ViewBag.Status = statusId == null ? Constant.DEFAULT : statusId;
            ViewBag.IsConfirm = isConfirm == null ? false : isConfirm;
            ViewBag.IsNotFinish = isNotFinish == null ? false : isNotFinish;
            return PartialView();
        }

        public virtual JsonResult Employees_Read([DataSourceRequest] DataSourceRequest request, string phothgraphId, int serviceTypeId,int? statusId, bool? isConfirm, bool? isNotFinish)
        {
            IQueryable<SchedulerViewModels> tasks = CreateEmployeeSchedules(phothgraphId, serviceTypeId, statusId, isConfirm, isNotFinish).Select(task => new SchedulerViewModels()
            {
                Id = task.Id,
                Title = task.Title,
                Description = task.Description,
                Start = task.Start,
                End = task.End,
                StartTimezone = task.StartTimezone,
                EndTimezone = task.EndTimezone,
                IsAllDay = task.IsAllDay,
                Recurrence = task.Recurrence,
                RecurrenceException = task.RecurrenceException,
                selectedStatus = task.selectedStatus
            }
            ).AsQueryable();
            return Json(tasks.ToDataSourceResult(request));
        }

        public virtual JsonResult Employees_Update([DataSourceRequest] DataSourceRequest request, SchedulerViewModels service)
        {
            if (ModelState.IsValid)
            {
                if (ValidateModel(service, ModelState))
                {
                    int? scheduleStatus = db.EmployeeSchedules.Find(service.Id).Status;
                    if (scheduleStatus != null)
                    {
                        if (ValidateServiceTableClass.ValidateStatus(service, ModelState, (int)scheduleStatus))
                        {
                            if (string.IsNullOrEmpty(service.Title))
                            {
                                service.Title = "";
                            }
                            var entity = db.EmployeeSchedules.FirstOrDefault(m => m.Id == service.Id);
                            //entity.StartTime = service.Start;
                            //entity.EndTime = service.End;
                            entity.Status = service.selectedStatus;
                            db.Entry(entity).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                        
                    }
                    
                }
            }

            return Json(new[] { service }.ToDataSourceResult(request, ModelState));
        }

        private bool ValidateModel(SchedulerViewModels service, ModelStateDictionary modelState)
        {
            if (service.Start > service.End)
            {
                modelState.AddModelError("errors", "End date must be greater or equal to Start date.");
                return false;
            }

            return true;
        }

        private List<SchedulerViewModels> CreateEmployeeSchedules(string photographId, int? serviceTypeId, int? statusId, bool? isConfirm, bool? isNotFinish)
        {
            List<SchedulerViewModels> _listSchecule = new List<SchedulerViewModels>();
            var allemployee = (from empSchedule in db.EmployeeSchedules
                              join emp in db.Employees on empSchedule.Employee.Id equals emp.Id
                              where (emp.EmployeePositions.FirstOrDefault().Id == Constant.EMPLOYEE_POSITION_PHOTOGRAPH || emp.EmployeePositions.FirstOrDefault().Id == Constant.EMPLOYEE_POSITION_CAMERAMAN)
                               select empSchedule).ToList();

            //Add condition for filtering
            var filterServiceForms = allemployee;
            if (photographId !=Constant.UNDEFINED && photographId != null)
            {
                filterServiceForms = filterServiceForms.Where(s => s.Employee.Id == photographId).Select(s => s).ToList();
            }

NicePictureStudio/NicePictureStudioWeb/Views/EmployeeSchedules/Delete.cshtml
@model NicePictureStudio.App_Data.EmployeeSchedule

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>EmployeeSchedule</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.StartTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.StartTime)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EndTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EndTime)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EmployeeServiceId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EmployeeServiceId)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

NicePictureStudio/NicePictureStudioWeb/Views/EmployeeSchedules/DetailsEmployee.cshtml
@model NicePictureStudio.Models.TableReportModel
@{
    ViewBag.Title = "รายละเอียดช่างถ่ายภาพ";
}

<script type="text/javascript">

    function PrintX()
    {
        $.print("#DetailsContainer");
    }
</script>

<div id="DetailsContainer">
    <h2>
        <span class="glyphicon glyphicon-heart-empty"></span>รายละเอียดการให้บริการช่างถ่ายภาพ (@Model.ServiceType) <br /><br />
        <button type="button" class="btn btn-warning btn-sm" onclick="window.open('@Url.Action("Edit", "Services", new { id=@Model.ServiceId })')"><span class="glyphicon glyphicon-heart-empty"></span>รายการที่เกี่ยวข้อง</button>
        <button type="button" class="btn btn-default btn-sm" onclick="PrintX()">พิมพ์</button>
    </h2>
    <br />

    <div class="panel panel-default">
        <div class="panel-heading">
            ข้อมูลทั่วไป
        </div>
        <div class="panel-body">
            <table class="table">
                <tr>
                    <!--Customer/Booking Section-->
                    <td rowspan="2">
                        <div class="panel panel-default">
                            <div class="panel-heading">รายละเอียดลูกค้า</div>
                            <div class="panel-body">
                                <div class="form-horizontal">
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("หมายเลขการจอง :")
                                            @Html.DisplayFor(model => model.BookingCode)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("ชื่อเจ้าบ่าว :")
                                            @Html.DisplayFor(model => model.Groom)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("ชื่อเจ้าสาว :")
                                            @Html.DisplayFor(model => model.Bride)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("คำขอร้องพิเศษ :")
                                            @Html.DisplayFor(model => model.BookingRequest)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("คำแนะนำพิเศษ :")
                                            @Html.DisplayFor(model => model.Suggestion)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("หมายเหตุ :")
                                            @Html.DisplayFor(model => model.Remark)
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="panel-heading">รายละเอียดการติดต่อลูกค้า</div>
                            <div class="panel-body">
                                <div class="form-group-sm">
                                    <div class="col-sm-12 text-left">
                                        @Html.Label("เบอร์โทรศัพท์เจ้าบ่าว :")
                                        @Html.DisplayFor(model => model.GroomPhone)
                                    </div>
                                </div>
                                <div class="form-group-sm">
                                    <div class="col-sm-12 text-left">
                                        @Html.Label("เบอร์โทรศัพท์เจ้าสาว :")
                                        @Html.DisplayFor(model => model.BridePhone)
                                    </div>
                                </div>
                                <div class="form-group-sm">
                                    <div class="col-sm-12 text-left">
                                        @Html.Label("อีเมลเจ้าบ่าว :")
                                        @Html.DisplayFor(model => model.GroomMail)
                                    </div>
                                </div>
                                <div class="form-group-sm">
                                    <div class="col-sm-12 text-left">
                                        @Html.Label("อีเมลเจ้าสาว :")
                                        @Html.DisplayFor(model => model.BrideMail)
                                    </div>
                                </div>
                                <div class="form-group-sm">
                                    <div class="col-sm-12 text-left">
                                        @Html.Label("ที่อยู่ลูกค้า :")
                                        @Html.DisplayFor(model => model.Address)
                                    </div>
                                </div>
                            </div>
                        </div>

                    </td>


                    <!--Location Section-->
                    <td>
                        <div class="panel panel-default">
                            <div class="panel-heading">รายละเอียดเวลาและสถานที่</div>
                            <div class="panel-body">
                                <div class="form-horizontal">
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("สถานที่ถ่ายภาพ :")
                                            @Html.DisplayFor(model => model.Location)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("รายละเอียด :")
                                            @Html.DisplayFor(model => model.LocationDetails)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("จำนวนแขกในงาน:")
                                            @Html.DisplayFor(model => model.GuestNumber) &nbsp; คน
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("เริ่มต้น :")
                                            @Html.DisplayFor(model => model.EventStart)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("สิ้นสุด :")
                                            @Html.DisplayFor(model => model.EventEnd)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("เบอร์โทรศัพท์ :")
                                            @Html.DisplayFor(model => model.LocatioNumber)
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </td>
                </tr>
                <tr>
                    <!--Photograph Section-->
                    <td>
                        <div class="panel panel-default">
                            <div class="panel-heading">รายละเอียดช่างภาพที่มีหน้าที่รับผิดชอบงาน</div>
                            <div class="panel-body">
                                <div class="form-horizontal">
                                    @foreach (var item in @Model.listEmployee)
                                    {
                                        <div class="row panel">
                                            <div class="form-group-sm">
                                                <div class="col-sm-12 text-left">
                                                    @Html.Label("ชื่อช่างถ่ายภาพ :")
                                                    @item.Name
                                                </div>
                                            </div>
                                            <div class="form-group-sm">
                                                <div class="col-sm-12 text-left">
                                                    @Html.Label("ตำแหน่ง :")
                                                    @item.Position
                                                </div>
                                            </div>
                                            <div class="form-group-sm">
                                                <div class="col-sm-12 text-left">
                                                    @Html.Label("เบอร์โทรศัพท์ :")
                                                    @item.PhoneNumber
                                                </div>
                                            </div>
                                            <div class="form-group-sm">
                                                <div class="col-sm-12 text-left">
                                                    @Html.Label("อีเมล :")
                                                    @item.Email
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>

        </div>
        @*<div class="panel-heading">รายละเอียดการให้บริการช่างถ่ายภาพ</div>
        <div class="panel-body">
            @{Html.RenderAction("DescriptionEmployee", "EmployeeSchedules", new { employeeScheduleId = @Model.OutsourceId, lstEmp = @Model.listEmployee });}
        </div>*@

    </div>

</div>

NicePictureStudio/NicePictureStudioWeb/Views/EmployeeSchedules/Index.cshtml
@model IEnumerable<NicePictureStudio.App_Data.EmployeeSchedule>

@{
    ViewBag.Title = "ตารางงานช่างถ่ายภาพ";
}
<script type="text/javascript">
    kendo.culture("th-TH");
    $(document).ready(function () {
        $("#statusId").on("change", function () {
            if ($("#statusId").val() >1)
            {
                $("#isConfirm").attr("disabled", "disabled");
                $("#isNotFinish").attr("disabled", "disabled");
                $("#lblIsConfirm").css("color", "#d2cdcd");
                $("#lblIsNotFinish").css("color", "#d2cdcd");
                $("#isNotFinish").attr("checked", false);
            }
            else if ($("#statusId").val() <= 1)
            {
                $("#isConfirm").attr("disabled", null);
                $("#isNotFinish").attr("disabled", null);
                $("#lblIsConfirm").css("color", "");
                $("#lblIsNotFinish").css("color", "");
            }
        });

        $("#ClearResult").on("click", function () {
            $("#isConfirm").attr("disabled", null);
            $("#isNotFinish").attr("disabled", null);
            $("#lblIsConfirm").css("color", "");
            $("#lblIsNotFinish").css("color", "");
        });
    });

    function modelOpen() {
        var serviceIndex = $(".IdEMPSchedule").val();
        $.ajax({
            url: '@Url.Action("DetailsEmployee", "EmployeeSchedules")',
            data: { EmployeeScheduleId: serviceIndex },
            type: "POST",
            success: function (data) {
                $(".nccontainer").html(data);
                $(".ncmodal").modal('toggle');

            }
        });
    }
</script>

<h2>ตารางงานช่างถ่ายภาพ บริษัท รูปสวยโฟโต้จำกัด</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<div class="panel-default table-bordered">
    <div class="panel-title"></div>
    <div class="panel-heading">ตัวเลือกในการค้นหาข้อมูล</div>
    <div class="panel-body">
        @using (Ajax.BeginForm("EmployeesScheduler", "EmployeeSchedules", new AjaxOptions
                        {
                            HttpMethod = "GET",
                            InsertionMode = InsertionMode.Replace,
                            UpdateTargetId = "ServiceFormsScheduler"
                        }))
        {
            <table class="table-responsive table">
                <tr>
                    <td>
                        <div class="form-horizontal">
                            <div class="form-group-sm">
                                <div class="col-sm-12 col-xs-3">@Html.Label("รายชื่อพนักงาน")</div>
                               
                                <div class="col-sm-12 col-xs-3">@(Html.Kendo().DropDownList().Name("photographId").BindTo(@ViewBag.EmployeeList as SelectList).HtmlAttributes(new { @style = "width:180px" }))</div>                    
                            </div>

                        </div>
                    </td>
                    <td>
                        <div class="col-sm-12 col-xs-3">@Html.Label("ประเภทของบริการ") </div>

                        <div class="col-sm-12 col-xs-3">@(Html.Kendo().DropDownList().Name("serviceTypeId").BindTo(@ViewBag.ServiceTypeList as SelectList).HtmlAttributes(new { @style = "width:160px" }))</div>
                    </td>
                    <td>
                        <div class="col-sm-12 col-xs-3">@Html.Label("สถานะ")</div>

                        <div class="col-sm-2 col-xs-3">@(Html.Kendo().DropDownList().Name("statusId").BindTo(@ViewBag.StatusList as SelectList).HtmlAttributes(new { @class = "statusId", @style = "width:150px" }))</div>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <hr />
                        <div class="form-horizontal">
                            <div class="panel-default table-bordered">
                                <div class="panel-heading">ตัวเลือกสำหรับรายการที่ยังไม่เสร็จสิ้นการให้บริการ</div>
                                <div class="panel-body">
                                    <div class="form-group-sm hidden">
                                        <div class="col-sm-1 col-xs-1 text-right"> @Html.CheckBox("isConfirm", false, new { @class = "form-contorl", @id = "isConfirm" })</div>
                                        <div class="col-sm-11 col-xs-5 text-left">@Html.Label("เลือกรายการที่ยังไม่ได้รับการยืนยันจากพนักงาน", new { @id = "lblIsConfirm" })</div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-1 col-xs-1 text-right"> @Html.CheckBox("isNotFinish", false, new { @class = "form-contorl", @id = "isNotFinish" })</div>
                                        <div class="col-sm-7 col-xs-11 text-left">@Html.Label("เลือกรายการที่ยังไม่เสร็จสิ้นและใกล้ถึงเวลาที่กำหนด", new { @id = "lblIsNotFinish" })</div>
                                    </div>
                                </div>
                            </div>

                        </div>

                    </td>
                </tr>
                <tr>
                    <td>
                        <button type="submit" value="GenerateFileter" class="btn-primary btn-md">เริ่มต้นค้นหา</button>
                        <button type="reset" id="ClearResult" value="GenerateFileter" class="btn-default btn-md">ล้างข้อมูลการค้นหา</button>
                    </td>
                </tr>
            </table>
        }
    </div>
</div>
<hr />
<div id="ServiceFormsScheduler">
    @{Html.RenderAction("EmployeesScheduler");}
</div>

<div class="modal fade ncmodal" id="NavPattern" tabindex="-10" role="dialog"
     aria-labelledby="NavService" aria-hidden="true" data-url='' data-servicetype="" style="position:fixed;z-index:10004">
    <div class="modal-dialog modal-lg" style="width:90%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">
                    ×
                </button>
                <h4 class="modal-title" id="NavModelPattern">
                    รายงานการให้บริการ บริษัทรูปสวยโฟโต้ จำกัด
                </h4>
            </div>
            <div class="modal-body">
                <div id="NavPatternBody" class="nccontainer"></div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnPrint" class="btn btn-default" onclick="PrintX()">พิมพ์</button>
                <button id="btnCancelPattern" type="button" class="btn btn-default"
                        data-dismiss="modal">
                    ปิดรายการ
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


    @*<p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <div id="ServiceFormsScheduler">
        @{Html.RenderAction("EmployeesScheduler");}
    </div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StartTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmployeeServiceId)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeServiceId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>*@