NicePictureStudio/NicePictureStudioWeb/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NicePictureStudio.App_Data;
using NicePictureStudio.Models;
using System.Data.Entity.Validation;
using System.Diagnostics;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using NicePictureStudio.Utils;

namespace NicePictureStudio
{
    public class ServicesController : Controller
    {
        private NicePictureStudioDBEntities db = new NicePictureStudioDBEntities();

        private ServicesViewModel _services;
        private ServicesViewModel _servicesEdit;
        private PromotionCalculator _promotionCalculator;
        private PromotionCalculator _promotionCalculatorEdit;
        private PromotionViewModel _promotion;

        private readonly int PREWEDDING_SERVICE = 1;
        private readonly int ENGAGEMENT_SERVICE = 2;
        private readonly int WEDDING_SERVICE = 3;

        private static readonly string CameraManType = "CameraMan";
        private static readonly string PhotographType = "PhotoGraph";
 
        //Command
        public static readonly string PreWedding = "PreWedding";
        public readonly string Engagement = "Engagement";
        public readonly string Wedding = "Wedding";
        public readonly string HTMLTagForReplace = "FormSection";
        public readonly string HTMLTagForDatePickerStart = "DatepickerStart";
        public readonly string HTMLTagForDatePickerEnd = "DatepickerEnd";
        
        //Modal
        public readonly string HTMLModalPhotoGraph = "modalPhotoGraph";
        public readonly string HTMLModalEquipment = "modalEquipment";
        public readonly string HTMLModalLocation = "modalLocation";
        public readonly string HTMLModalOutSource = "modalOutsource";
        public readonly string HTMLModalOutput = "modalOutput";

        public readonly string HTMLModalPhotoGraphArrow = "modalPhotoGraphArrow";
        public readonly string HTMLModalEquipmentArrow = "modalEquipmentArrow";
        public readonly string HTMLModalLocationArrow = "modalLocationArrow";
        public readonly string HTMLModalOutSourceArrow = "modalOutsourceArrow";
        public readonly string HTMLModalOutputArrow = "modalOutput";
        
        //Button
        public readonly string HTMLTagButtonPhotoGraph = "btnPhotoGraph";
        public readonly string HTMLTagButtonEquipment = "btnEquipment";
        public readonly string HTMLTagButtonLocation = "btnLocation";
        public readonly string HTMLTagButtonOutSource = "btnOutsource";
        public readonly string HTMLTagButtonOutput = "btnOutput";
        //Container
        public readonly string HTMLContainerButtonPhotoGraph = "ctnPhotoGraph";
        public readonly string HTMLContainerButtonEquipment = "ctnEquipment";
        public readonly string HTMLContainerButtonLocation = "ctnLocation";
        public readonly string HTMLContainerButtonOutSource = "ctnOutsource";
        public readonly string HTMLContainerButtonOutput = "ctnOutput";

        //DropDownList naming for each division
        //Add Photograph Service Page
        public readonly string HTMLDWLPhotoGraphEngagementServices = "dwlPhotoGraphEngagementService";
        public readonly string HTMLDWLPhotoGraphPreWeddingServices = "dwlPhotoGraphPreWeddingService";
        public readonly string HTMLDWLPhotoGraphWeddingServices = "dwlPhotoGraphWeddingService";

        //Add Equipment Service Page
        public readonly string HTMLDWLEquipmentEngagementServices = "dwlEquipmentEngagementService";
        public readonly string HTMLDWLEquipmentPreWeddingServices = "dwlEquipmentPreWeddingService";
        public readonly string HTMLDWLEquipmentWeddingServices = "dwlEquipmentWeddingService";

        public readonly string HTMLTableEquipmentEngagementServices = "tblEquipmentEngagementService";
        public readonly string HTMLTableEquipmentPreWeddingServices = "tblEquipmentPreWeddingService";
        public readonly string HTMLTableEquipmentWeddingServices = "tblEquipmentWeddingService";

        //Add Location Service Page
        public readonly string HTMLDWLLocationEngagementServices = "dwlLocationEngagementService";
        public readonly string HTMLDWLLocationPreWeddingServices = "dwlLocationPreWeddingService";
        public readonly string HTMLDWLLocationWeddingServices = "dwlLocationWeddingService";

        //Add Outsource Service Page
        public readonly string HTMLDWLOutsourceEngagementServices = "dwlOutsourceEngagementService";
        public readonly string HTMLDWLOutsourcePreWeddingServices = "dwlOutsourcePreWeddingService";
        public readonly string HTMLDWLOutsourceWeddingServices = "dwlOutsourceWeddingService";

        //Add Output Service Page
        public readonly string HTMLDWLOutputEngagementServices = "dwlOutputEngagementService";
        public readonly string HTMLDWLOutputPreWeddingServices = "dwlOutputPreWeddingService";
        public readonly string HTMLDWLOutputWeddingServices = "dwlOutputWeddingService";
        /******************************************************************************************************/

        //Create Service Form by division
        //Add Photograph Service Page
        public readonly string HTMLPhotoServiceModalPreWedding = "divPhotoGraphPreWedding";
        public readonly string HTMLPhotoServiceModalEngagement = "divPhotoGraphEngagement";
        public readonly string HTMLPhotoServiceModalWedding = "divPhotoGraphWedding";

        //Add Equipment Service Page
        public readonly string HTMLEquipmentModalPreWedding = "divEquipmentPreWedding";
        public readonly string HTMLEquipmentModalEngagement = "divEquipmentEngagement";
        public readonly string HTMLEquipmentModalWedding = "divEquipmentWedding";

        //Add Location Service Page
        public readonly string HTMLLocationModalPreWedding = "divLocationPreWedding";
        public readonly string HTMLLocationModalEngagement = "divLocationEngagement";
        public readonly string HTMLLocationModalWedding = "divLocationWedding";

        //Add Outsource Service Page
        public readonly string HTMLOutsourceModalPreWedding = "divOutsourcePreWedding";
        public readonly string HTMLOutsourceModalEngagement = "divOutsourceEngagement";
        public readonly string HTMLOutsourceModalWedding = "divOutsourceWedding";

        //Add Outsource Service Page
        public readonly string HTMLOutputModalPreWedding = "divOutputPreWedding";
        public readonly string HTMLOutputModalEngagement = "divOutputEngagement";
        public readonly string HTMLOutputModalWedding = "divOutputWedding";
        /******************************************************************************************************/

        //CreateCollapse form by division
        //Add Photograph Service Page
        public readonly string HTMLCollapsePhotoPreWedding = "collPhotoGraphPreWedding";
        public readonly string HTMLCollapsePhotoEngagement = "collPhotoGraphEngagement";
        public readonly string HTMLCollapsePhotoWedding = "collPhotoGraphWedding";

        public readonly string HTMLCollapseCameraPreWedding = "collCameraPreWedding";
        public readonly string HTMLCollapseCameraEngagement = "collCameraEngagement";
        public readonly string HTMLCollapseCameraWedding = "collCameraWedding";
        /******************************************************************************************************/

        //Create Table form by division
        //Add Equipment Service Page
        public readonly string HTMLTableEquipmentPreWedding = "tblEquipmentPreWedding";
        public readonly string HTMLTableEquipmentEngagement = "tblEquipmentEngagement";
        public readonly string HTMLTableEquipmentWedding = "tblEquipmentWedding";

        //Add Location Service Page
        public readonly string HTMLTableLocationPreWedding = "tblLocationPreWedding";
        public readonly string HTMLTableLocationEngagement = "tblLocationEngagement";
        public readonly string HTMLTableLocationWedding = "tblLocationWedding";

        //Add Location Service Page
        public readonly string HTMLTableOutsourcePreWedding = "tblOutsourcePreWedding";
        public readonly string HTMLTableOutsourceEngagement = "tblOutsourceEngagement";
        public readonly string HTMLTableOutsourceWedding = "tblOutsourceWedding";

        //Add Location Service Page
        public readonly string HTMLTableOutputPreWedding = "tblOutputPreWedding";
        public readonly string HTMLTableOutputEngagement = "tblOutputEngagement";
        public readonly string HTMLTableOutputWedding = "tblOutputWedding";

        public readonly string HTMLButtonEnabledForm = "btnEnabled";
        public readonly string HTMLButtonDisabledForm = "btnDisabled";
        /******************************************************************************************************/

        // GET: Services
        public async Task<ActionResult> Index()
        {
            var services = db.Services.Include(s => s.Customer);
            return View(await services.ToListAsync());
        }

        public ActionResult IndexServicesCRM()
        {
            return View();
        }

        public ActionResult ServicesCostReport(int? serviceId)
        {
            ViewBag.ServiceId = serviceId;
            return View();
        }

        public ActionResult Services_read([DataSourceRequest] DataSourceRequest request)
        {
            var services = db.Services.Include(s => s.Customer);

            IQueryable<ServiceGridViewModel> tasks = services.Select(task => new ServiceGridViewModel()
            {
                Id = task.Id,
                BookingName = task.BookingName,
                BrideName = task.BrideName,
                GroomName = task.GroomName,
                PayAmount = task.PayAmount,
                Payment = task.Payment,

NicePictureStudio/NicePictureStudioWeb/Views/EquipmentSchedules/Create.cshtml
@model NicePictureStudio.App_Data.EquipmentSchedule

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>EquipmentSchedule</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.EquipmentId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EquipmentId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EquipmentId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.EquipmentServiceId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EquipmentServiceId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EquipmentServiceId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

NicePictureStudio/NicePictureStudioWeb/Views/EquipmentSchedules/Delete.cshtml
@model NicePictureStudio.App_Data.EquipmentSchedule

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>EquipmentSchedule</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.StartTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.StartTime)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EndTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EndTime)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EquipmentId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EquipmentId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EquipmentServiceId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EquipmentServiceId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

NicePictureStudio/NicePictureStudioWeb/Views/EquipmentSchedules/Details.cshtml
@model NicePictureStudio.App_Data.EquipmentSchedule

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>EquipmentSchedule</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.StartTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.StartTime)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EndTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EndTime)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EquipmentId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EquipmentId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EquipmentServiceId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EquipmentServiceId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

NicePictureStudio/NicePictureStudioWeb/Views/EquipmentSchedules/DetailsEquipment.cshtml
@model NicePictureStudio.Models.TableReportModel

@{
    ViewBag.Title = "รายละเอียดตารางอุปกรณ์";
}

<script type="text/javascript">

    function PrintX(){
        $.print("#DetailsContainer");
    }
</script>

<div id="DetailsContainer">
    <h2>
        <span class="glyphicon glyphicon-heart-empty"></span>รายละเอียดสำหรัการจัดเตรียมอุปกรณ์ (@Model.ServiceType) <br /><br />
        <button type="button" class="btn btn-warning btn-sm" onclick="window.open('@Url.Action("Edit", "Services", new { id=@Model.ServiceId })')"><span class="glyphicon glyphicon-heart-empty"></span>รายการที่เกี่ยวข้อง</button>
        <button type="button" class="btn btn-default btn-sm" onclick="PrintX()">พิมพ์</button>
    </h2>
    <br />

    <div class="panel panel-default">
        <div class="panel-heading">
            ข้อมูลทั่วไป
        </div>
        <div class="panel-body">
            <table class="table">
                <tr>
                    <!--Customer/Booking Section-->
                    <td rowspan="2">
                        <div class="panel panel-default">
                            <div class="panel-heading">รายละเอียดลูกค้า</div>
                            <div class="panel-body">
                                <div class="form-horizontal">
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("หมายเลขการจอง :")
                                            @Html.DisplayFor(model => model.BookingCode)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("ชื่อเจ้าบ่าว :")
                                            @Html.DisplayFor(model => model.Groom)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("ชื่อเจ้าสาว :")
                                            @Html.DisplayFor(model => model.Bride)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("คำขอร้องพิเศษ :")
                                            @Html.DisplayFor(model => model.BookingRequest)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("คำแนะนำพิเศษ :")
                                            @Html.DisplayFor(model => model.Suggestion)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("หมายเหตุ :")
                                            @Html.DisplayFor(model => model.Remark)
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="panel-heading">รายละเอียดการติดต่อลูกค้า</div>
                            <div class="panel-body">
                                <div class="form-group-sm">
                                    <div class="col-sm-12 text-left">
                                        @Html.Label("เบอร์โทรศัพท์เจ้าบ่าว :")
                                        @Html.DisplayFor(model => model.GroomPhone)
                                    </div>
                                </div>
                                <div class="form-group-sm">
                                    <div class="col-sm-12 text-left">
                                        @Html.Label("เบอร์โทรศัพท์เจ้าสาว :")
                                        @Html.DisplayFor(model => model.BridePhone)
                                    </div>
                                </div>
                                <div class="form-group-sm">
                                    <div class="col-sm-12 text-left">
                                        @Html.Label("อีเมลเจ้าบ่าว :")
                                        @Html.DisplayFor(model => model.GroomMail)
                                    </div>
                                </div>
                                <div class="form-group-sm">
                                    <div class="col-sm-12 text-left">
                                        @Html.Label("อีเมลเจ้าสาว :")
                                        @Html.DisplayFor(model => model.BrideMail)
                                    </div>
                                </div>
                                <div class="form-group-sm">
                                    <div class="col-sm-12 text-left">
                                        @Html.Label("ที่อยู่ลูกค้า :")
                                        @Html.DisplayFor(model => model.Address)
                                    </div>
                                </div>
                            </div>
                        </div>

                    </td>


                    <!--Location Section-->
                    <td>
                        <div class="panel panel-default">
                            <div class="panel-heading">รายละเอียดเวลาและสถานที่</div>
                            <div class="panel-body">
                                <div class="form-horizontal">
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("สถานที่ถ่ายภาพ :")
                                            @Html.DisplayFor(model => model.Location)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("รายละเอียด :")
                                            @Html.DisplayFor(model => model.LocationDetails)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("จำนวนแขกในงาน:")
                                            @Html.DisplayFor(model => model.GuestNumber) &nbsp; คน
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("เริ่มต้น :")
                                            @Html.DisplayFor(model => model.EventStart)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("สิ้นสุด :")
                                            @Html.DisplayFor(model => model.EventEnd)
                                        </div>
                                    </div>
                                    <div class="form-group-sm">
                                        <div class="col-sm-12 text-left">
                                            @Html.Label("เบอร์โทรศัพท์ :")
                                            @Html.DisplayFor(model => model.LocatioNumber)
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </td>
                </tr>
                <tr>
                    <!--Photograph Section-->
                    <td>
                        <div class="panel panel-default">
                            <div class="panel-heading">รายละเอียดช่างภาพที่มีหน้าที่รับผิดชอบงาน</div>
                            <div class="panel-body">
                                <div class="form-horizontal">
                                    @foreach (var item in @Model.listEmployee)
                                    {
                                        <div class="row panel">
                                            <div class="form-group-sm">
                                                <div class="col-sm-12 text-left">
                                                    @Html.Label("ชื่อช่างถ่ายภาพ :")
                                                    @item.Name
                                                </div>
                                            </div>
                                            <div class="form-group-sm">
                                                <div class="col-sm-12 text-left">
                                                    @Html.Label("ตำแหน่ง :")
                                                    @item.Position
                                                </div>
                                            </div>
                                            <div class="form-group-sm">
                                                <div class="col-sm-12 text-left">
                                                    @Html.Label("เบอร์โทรศัพท์ :")
                                                    @item.PhoneNumber
                                                </div>
                                            </div>
                                            <div class="form-group-sm">
                                                <div class="col-sm-12 text-left">
                                                    @Html.Label("อีเมล :")
                                                    @item.Email
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>

        </div>
        <div class="panel-heading">รายละเอียดอุปกรณ์</div>
        <div class="panel-body">
            @(Html.Kendo().Grid<NicePictureStudio.App_Data.Equipment>()
            .Name("EquipmentDetails")
            .Columns(columns =>
            {
                columns.Bound(p => p.EquipmentName).Filterable(false).Width(100).Title("ชื่ออุปกรณ์");
               // columns.Bound(p => p.EquipmentDetail).Width(100);
               // columns.Bound(p => p.Quantity).Format("{0:MM/dd/yyyy}").Width(140);
                columns.Bound(p => p.ModelName).Width(150).Title("รุ่น");
                columns.Bound(p => p.Quantity).Width(50).Title("จำนวน");
                
            })
            //.Pageable()
            .Sortable()
            .Scrollable()
            //.Filterable()
            .HtmlAttributes(new { style = "height:300px;" })
            .DataSource(dataSource => dataSource
                .Ajax()
                .PageSize(15)
                .Read(read => read.Action("EquipmentSets_Read", "EquipmentSchedules", new { serviceId = @ViewBag.EquipmentSetId }))
             )
            )

        </div>
    </div>

</div>

NicePictureStudio/NicePictureStudioWeb/Views/EquipmentSchedules/GetRemainNumberFromDatabase.cshtml
@model Int32
    <div data-container-for="RemainItem" class="k-edit-field RemainItem">
        <div class="input-group">
            @(Html.TextBox("RemainItem", @Model, new { @class = "k-textbox", data_bind = "value:RemainItem", @disabled = "true" }))
            <span class="input-group-btn col-sm-pull-5"><button class="btn btn-default" onclick="getRemainValue()">refresh</button></span>
        </div>
    </div>