NicePictureStudio/NicePictureStudioWeb/Controllers/CRMTemplatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NicePictureStudio.App_Data;
using NicePictureStudio.Models;
using NicePictureStudio.Utils;
using System.Web.Http.Cors;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;

namespace NicePictureStudio
{
    public class CRMTemplatesController : Controller
    {
        private NicePictureStudioDBEntities db = new NicePictureStudioDBEntities();

        // GET: CRMTemplates
        public async Task<ActionResult> Index()
        {
            var cRMTemplates = db.CRMTemplates.Include(c => c.CRMServiceCategory).Include(c => c.CRMServiceType);
            return View(await cRMTemplates.ToListAsync());
        }

        public ActionResult IndexCRM()
        {
            return View();
        }

        public ActionResult CreateCRMFrom(int? id)
        {
            if(id !=null)
            {
                var service = db.Services.Find(id);
                if (service != null)
                {
                    CRMForm crmForm = new CRMForm();
                    db.CRMForms.Add(crmForm);
                    db.SaveChanges();

                    service.CRMFormId = crmForm.Id;
                    db.Entry(service).State = EntityState.Modified;

                    db.SaveChanges();

                    return RedirectToAction("CRMApprisalGen", new { id=crmForm.Id });
                }
                else 
                {
                    return View();
                }
            }
            return View();

        }

        public ActionResult Services_read([DataSourceRequest] DataSourceRequest request)
        {

            var newList = CreateServiceGrideCRM().OrderBy(s => s.IsApprisalReady).Reverse();
            IQueryable<ServiceGridViewModel> tasks = newList.Select(task => new ServiceGridViewModel()
            {
                Id = task.Id,
                BookingName = task.BookingName,
                BrideName = task.BrideName,
                GroomName = task.GroomName,
                PayAmount = task.PayAmount,
                Payment = task.Payment,
                CustomerName = task.CustomerName,
                ServiceStatus = task.ServiceStatus,
                SpecialRequest = task.SpecialRequest,
                CurrentStatus =task.CurrentStatus,
                Email = task.Email,
                PhoneNumber = task.PhoneNumber,
                ServiceStatusText = task.ServiceStatusText
            }
             ).AsQueryable();
            return Json(tasks.ToDataSourceResult(request));
        }

        private List<ServiceGridViewModel> CreateServiceGrideCRM()
        {
            var services = db.Services.Include(s => s.Customer).Where(s=>s.CRMFormId == null);
            List<ServiceGridViewModel> _listServices = new List<ServiceGridViewModel>();
            foreach (var item in services)
            {
                var statusText = AnalysisServiceStatus(item);
                var service = new ServiceGridViewModel { 
                Id  = item.Id,
                BookingName = item.BookingName,
                BrideName = item.BrideName,
                GroomName = item.GroomName,
                CustomerName = item.GroomName + " / " + item.BrideName,
                Email = item.Customer.Email + " / " + item.Customer.CoupleEmail,
                PhoneNumber = item.Customer.PhoneNumber + " / " + item.Customer.CouplePhoneNumber,
                ServiceStatus = item.ServiceStatu.StatusName,
                CurrentStatus = item.ServiceStatu.Id,
                ServiceStatusText = statusText,
                IsApprisalReady = statusText == Constant.SERVICE_FORM_STATUS_FINISH ? true : statusText ==Constant.SERVICE_FORM_STATUS_CANCEL ?  true : false
                };
                _listServices.Add(service);
            }
            return _listServices;
        }

        private string AnalysisServiceStatus(Service service)
        {
            var lstServiceForm = service.ServiceForms;
            var IsNew = lstServiceForm.All(s => s.ServiceStatu.Id <= Constant.SERVICE_STATUS_NEW);
            if (lstServiceForm.All(s => s.ServiceStatu.Id <= Constant.SERVICE_STATUS_NEW))
            {
                return Constant.SERVICE_FORM_STATUS_NEW;
            }
            else if (lstServiceForm.All(s => s.ServiceStatu.Id == Constant.SERVICE_STATUS_CONFIRM))
            {
                return Constant.SERVICE_FORM_STATUS_CONFIRM;
            }
            else if (lstServiceForm.All(s => s.ServiceStatu.Id <= Constant.SERVICE_STATUS_CONFIRM))
            {
                return Constant.SERVICE_FORM_STATUS_PARTIAL_NEW;
            }
            else if (lstServiceForm.All(s => s.ServiceStatu.Id == Constant.SERVICE_STATUS_COMPLETE))
            {
                return Constant.SERVICE_FORM_STATUS_FINISH;
            }
            else if (lstServiceForm.All(s => s.ServiceStatu.Id <= Constant.SERVICE_STATUS_COMPLETE))
            {
                return Constant.SERVICE_FORM_STATUS_PARTIAL_FINISH;
            }
            else if (lstServiceForm.All(s => s.ServiceStatu.Id == Constant.SERVICE_STATUS_CANCEL))
            {
                return Constant.SERVICE_FORM_STATUS_CANCEL;
            }
            else if (lstServiceForm.All(s => s.ServiceStatu.Id <= Constant.SERVICE_STATUS_CANCEL))
            {
                return Constant.SERVICE_FORM_STATUS_PARTIAL_CANCEL;
            }
            else if (lstServiceForm.All(s => s.ServiceStatu.Id == Constant.SERVICE_STATUS_CANCEL_IN7DAYS))
            {
                return Constant.SERVICE_FORM_STATUS_CANCEL;
            }
            else if (lstServiceForm.All(s => s.ServiceStatu.Id <= Constant.SERVICE_STATUS_CANCEL_IN7DAYS))
            {
                return Constant.SERVICE_FORM_STATUS_PARTIAL_CANCEL;
            }
            else if (lstServiceForm.All(s => s.ServiceStatu.Id == Constant.SERVICE_STATUS_WARNING))
            {
                return Constant.SERVICE_FORM_STATUS_PARTIAL_NEW;
            }
            else if (lstServiceForm.All(s => s.ServiceStatu.Id <= Constant.SERVICE_STATUS_WARNING))
            {
                return Constant.SERVICE_FORM_STATUS_PARTIAL_NEW;
            }
            else
            {
                return string.Empty;
            }
        }

        // GET: CRMTemplates/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CRMTemplate cRMTemplate = await db.CRMTemplates.FindAsync(id);
            if (cRMTemplate == null)
            {
                return HttpNotFound();
            }
            return View(cRMTemplate);
        }

        // GET: CRMTemplates/Create
        public ActionResult Create()
        {
            ViewBag.ServiceCategory = new SelectList(db.CRMServiceCategories, "Id", "Name");
            ViewBag.ServiceType = new SelectList(db.CRMServiceTypes, "Id", "Name");
            return View();
        }

        // POST: CRMTemplates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Question,ServiceCategory,ServiceType")] CRMTemplate cRMTemplate)
        {
            if (ModelState.IsValid)
            {
                db.CRMTemplates.Add(cRMTemplate);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ServiceCategory = new SelectList(db.CRMServiceCategories, "Id", "Name", cRMTemplate.ServiceCategory);
            ViewBag.ServiceType = new SelectList(db.CRMServiceTypes, "Id", "Name", cRMTemplate.ServiceType);
            return View(cRMTemplate);
        }

        // GET: CRMTemplates/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CRMTemplate cRMTemplate = await db.CRMTemplates.FindAsync(id);
            if (cRMTemplate == null)
            {
                return HttpNotFound();
            }
            ViewBag.ServiceCategory = new SelectList(db.CRMServiceCategories, "Id", "Name", cRMTemplate.ServiceCategory);
            ViewBag.ServiceType = new SelectList(db.CRMServiceTypes, "Id", "Name", cRMTemplate.ServiceType);
            return View(cRMTemplate);
        }

        // POST: CRMTemplates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Question,ServiceCategory,ServiceType")] CRMTemplate cRMTemplate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cRMTemplate).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ServiceCategory = new SelectList(db.CRMServiceCategories, "Id", "Name", cRMTemplate.ServiceCategory);
            ViewBag.ServiceType = new SelectList(db.CRMServiceTypes, "Id", "Name", cRMTemplate.ServiceType);
            return View(cRMTemplate);
        }

        // GET: CRMTemplates/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

NicePictureStudio/NicePictureStudioWeb/Views/CRMTemplates/CRMApprisal.cshtml
@model NicePictureStudio.Models.CRMModel

<h2>สวัสดี คุณ @Model.CustomerName</h2>    
<p>ขอความกรุณาตอบแบบประเมินการให้บริการ ของ บริษัท รูปสวยโฟโต้ จำกัด</p>

@using (@Ajax.BeginForm("CRMApprisal", "CRMTemplates", new AjaxOptions
                {
                    HttpMethod = "POST",
                    //InsertionMode = InsertionMode.Replace,
                    //UpdateTargetId = "MainSection"
                }
                ))
{
    @Html.AntiForgeryToken()

    <table class="table table-bordered table-striped" cellspacing="0" id="tblServices">
    <thead>
        <tr>
            <th rowspan="2" class="col-md-2 col-lg-5 text-center" style="vertical-align:middle">
                @Html.DisplayName("แบบประเมิน")
            </th>
            <th colspan="6" align="center" class="text-center">@Html.DisplayName("คะแนนความพึงพอใจ")</th>
        </tr>
        <tr>
            <th class="col-md-2 col-lg-1 text-center" align="center">
                @Html.DisplayName("ไม่มีความเห็น")
            </th>
            <th class="col-md-2 col-lg-1 text-center" align="center">
                @Html.DisplayName("ไม่พอใจมาก")
            </th>
            <th class="col-md-2 col-lg-1 text-center" align="center">
                @Html.DisplayName("ไม่พอใจ")
            </th>
            <th class="col-md-2 col-lg-1 text-center" align="center">
                @Html.DisplayName("เฉยๆ")
            </th>
            <th class="col-md-2 col-lg-1 text-center" align="center">
                @Html.DisplayName("พอใจ")
            </th>
            <th class="col-md-2 col-lg-1 text-center" align="center">
             @Html.DisplayName("พอใจมาก")
            </th>
</tr>

    </thead>
    <tbody>
            @*@foreach (NicePictureStudio.Models.Question item in @Model.Questions)
            {
                <tr>
                    <td><div>@Html.HiddenFor()</div><div>@item.QuestionText</div></td>
                    <td>
                        <div class="btn-group" id="ABC">
                            <label class="radio-inline">
                                <input type="radio" name="@item.Id" id="@item.Id" value="option1"> 1
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="@item.Id" id="@item.Id" value="option2"> 2
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="@item.Id" id="@item.Id" value="option3"> 3
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="@item.Id" id="@item.Id" value="option4"> 4
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="@item.Id" id="@item.Id" value="option5"> 5
                            </label>
                        </div>
                    </td>
                </tr>
            }*@
       @Html.EditorFor(x=>x.Questions)
        <tr>
            <td colspan="6"align="center" >
                <h4>ข้อเสนอแนะเพิ่มเติม : </h4>
                <div>
                    @Html.TextArea("TxtArea", new { @rows=10,@cols=250,@style="max-width:500px" })
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="6" align="center">
                <input type="submit" class="btn btn-primary" value="Submit" />
            </td>
        </tr>
    </tbody>
    
</table>
}
@*@using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Customer</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.PostcalCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PostcalCode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PostcalCode, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.AnniversaryDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AnniversaryDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AnniversaryDate, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ReferencePerson, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReferencePerson, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReferencePerson, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ReferenceEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReferenceEmail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReferenceEmail, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ReferencePhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReferencePhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReferencePhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

NicePictureStudio/NicePictureStudioWeb/Views/CRMTemplates/CRMApprisalGen.cshtml
@model NicePictureStudio.Models.CRMModel
           
<script type="text/javascript">

</script>


<h2>สวัสดี คุณ @Model.CustomerName</h2>    
<p>ขอความกรุณาตอบแบบประเมินการให้บริการ ของ บริษัท รูปสวยโฟโต้ จำกัด</p>

    @using (@Ajax.BeginForm("CRMApprisalGen", "CRMTemplates", new AjaxOptions
                {
                    HttpMethod = "POST",
                    OnBegin = "return checkData()",
                    OnSuccess = "window.location.href = '/CRMTemplates/FinishingApprisal' "
                }
                ))
    {
    @Html.AntiForgeryToken()

    <table class="table table-bordered table-striped" cellspacing="0" id="tblServices">
    <thead>
        <tr>
            <th rowspan="2" class="col-md-2 col-lg-5 text-center" style="vertical-align:middle;width:300px;">
                @Html.HiddenFor(model => model.Id)
                @Html.DisplayName("แบบประเมิน")
            </th>
            <th colspan="6" align="center" class="text-center">@Html.DisplayName("คะแนนความพึงพอใจ")</th>
        </tr>
        <tr>
            @*<th class="col-md-2 col-lg-1 text-center" align="center">
                @Html.DisplayName("ไม่มีความเห็น")
            </th>*@
            <th class="col-md-2 col-lg-1 text-center" align="center">
                @Html.DisplayName("ไม่พอใจมาก")
            </th>
            <th class="col-md-2 col-lg-1 text-center" align="center">
                @Html.DisplayName("ไม่พอใจ")
            </th>
            <th class="col-md-2 col-lg-1 text-center" align="center">
                @Html.DisplayName("เฉยๆ")
            </th>
            <th class="col-md-2 col-lg-1 text-center" align="center">
                @Html.DisplayName("พอใจ")
            </th>
            <th class="col-md-2 col-lg-1 text-center" align="center">
             @Html.DisplayName("พอใจมาก")
            </th>
</tr>

    </thead>
    <tbody>

       @Html.EditorFor(x=>x.Questions)
        <tr>
            <td colspan="6"align="center" >
                <h4>ข้อเสนอแนะเพิ่มเติม : </h4>
                <div>
                    @Html.TextArea("TxtArea", new { @rows=10,@cols=250,@style="max-width:500px" })
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="6" align="center">
                <button type="submit" class="btn btn-primary" value="Submit">ส่งผลการประเมิน</button>
            </td>
        </tr>
    </tbody>
    
</table>
}


<script type="text/javascript">
    function checkData()
    {
        var Q1 = $('input:radio[id=Questions_0__SelectedAnswer]:checked').val()
        var Q2 = $('input:radio[id=Questions_1__SelectedAnswer]:checked').val()
        var Q3 = $('input:radio[id=Questions_2__SelectedAnswer]:checked').val()
        var Q4 = $('input:radio[id=Questions_3__SelectedAnswer]:checked').val()
        var Q5 = $('input:radio[id=Questions_4__SelectedAnswer]:checked').val()
        var Q6 = $('input:radio[id=Questions_5__SelectedAnswer]:checked').val()
        var Q7 = $('input:radio[id=Questions_6__SelectedAnswer]:checked').val()
        var Q8 = $('input:radio[id=Questions_6__SelectedAnswer]:checked').val()
        if(Q1 != undefined && Q2 != undefined && Q3 != undefined && Q4 != undefined && Q5 != undefined && Q6 != undefined && Q7 != undefined)
        {
            return true;
        }
        else
        {
            alert("กรุณาตอบคำถามให้ครบส่งผลการประเมิน ขอบคุณครับ");
            return false;
            
        }
    }
</script>
@*@using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Customer</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.PostcalCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PostcalCode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PostcalCode, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.AnniversaryDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AnniversaryDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AnniversaryDate, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ReferencePerson, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReferencePerson, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReferencePerson, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ReferenceEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReferenceEmail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReferenceEmail, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ReferencePhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReferencePhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReferencePhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

NicePictureStudio/NicePictureStudioWeb/Views/CRMTemplates/CRMCustomerRelation.cshtml
@model IEnumerable<NicePictureStudio.Models.CustomerRelation>

@{
    ViewBag.Title = "ลูกค้าสัมพันธ์";
}

<script type="text/javascript">
    kendo.culture("th-TH");
</script>

<div id="CustomerRelationSection">
    <hr />
    <table class="table table-responsive table-bordered  table-striped">
        <tr class="success">
            <th class="text-center">
                @Html.DisplayName("ชื่อลูกค้า")
            </th>
            <th class="text-center">
                @Html.DisplayName("หมายเลขโทรศัพท์")
            </th>
            <th class="text-center">
                @Html.DisplayName("อีเมล")
            </th>
            <th class="text-center">
                @Html.DisplayName("ที่อยู่")
            </th>
            <th class="text-center">
                @Html.DisplayName("วันครบรอบแต่งงาน")
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerPhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerEmail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerAddress)
                </td>
                <td>
                    @Html.ValueFor(modelItem => item.AnniversaryDate, "{0:dd/MM/yyyy}")
                </td>
            </tr>
        }
    </table>

</div>

NicePictureStudio/NicePictureStudioWeb/Views/CRMTemplates/CreateCRMFrom.cshtml
@{
    ViewBag.Title = "CreateCRMFrom";
}

<h2>ไม่พบแบบประเมินที่คุณต้องการสร้าง กรุณาติดต่อผู้ดูแลระบบ</h2>